name: Update README Badges

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Update README badges
        run: |
          # Get version from package.json
          VERSION=$(node -p "require('./package.json').version")

          # Get coverage from coverage report
          COVERAGE=$(node -p "Math.round(require('./coverage/coverage-summary.json').total.lines.pct)")

          # Update README.md
          sed -i "s/version-[0-9.]*-blue/version-$VERSION-blue/" README.md
          sed -i "s/coverage-[0-9]*%25-green/coverage-$COVERAGE%25-green/" README.md

          # Update Chinese README if exists
          if [ -f "README.zh.md" ]; then
            sed -i "s/version-[0-9.]*-blue/version-$VERSION-blue/" README.zh.md
            sed -i "s/coverage-[0-9]*%25-green/coverage-$COVERAGE%25-green/" README.zh.md
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md README.zh.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update README badges [skip ci]"
          git push
